// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210211.2

#ifndef WINRT_Windows_Media_Capture_1_H
#define WINRT_Windows_Media_Capture_1_H
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Windows.Storage.Streams.0.h"
#include "winrt/impl/Windows.Media.Capture.0.h"
WINRT_EXPORT namespace winrt::Windows::Media::Capture
{
    struct __declspec(empty_bases) IAdvancedCapturedPhoto :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAdvancedCapturedPhoto>
    {
        IAdvancedCapturedPhoto(std::nullptr_t = nullptr) noexcept {}
        IAdvancedCapturedPhoto(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAdvancedCapturedPhoto(IAdvancedCapturedPhoto const&) noexcept = default;
        IAdvancedCapturedPhoto(IAdvancedCapturedPhoto&&) noexcept = default;
        IAdvancedCapturedPhoto& operator=(IAdvancedCapturedPhoto const&) & noexcept = default;
        IAdvancedCapturedPhoto& operator=(IAdvancedCapturedPhoto&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAdvancedCapturedPhoto2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAdvancedCapturedPhoto2>
    {
        IAdvancedCapturedPhoto2(std::nullptr_t = nullptr) noexcept {}
        IAdvancedCapturedPhoto2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAdvancedCapturedPhoto2(IAdvancedCapturedPhoto2 const&) noexcept = default;
        IAdvancedCapturedPhoto2(IAdvancedCapturedPhoto2&&) noexcept = default;
        IAdvancedCapturedPhoto2& operator=(IAdvancedCapturedPhoto2 const&) & noexcept = default;
        IAdvancedCapturedPhoto2& operator=(IAdvancedCapturedPhoto2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAdvancedPhotoCapture :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAdvancedPhotoCapture>
    {
        IAdvancedPhotoCapture(std::nullptr_t = nullptr) noexcept {}
        IAdvancedPhotoCapture(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAdvancedPhotoCapture(IAdvancedPhotoCapture const&) noexcept = default;
        IAdvancedPhotoCapture(IAdvancedPhotoCapture&&) noexcept = default;
        IAdvancedPhotoCapture& operator=(IAdvancedPhotoCapture const&) & noexcept = default;
        IAdvancedPhotoCapture& operator=(IAdvancedPhotoCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastBackgroundService :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastBackgroundService>
    {
        IAppBroadcastBackgroundService(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastBackgroundService(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastBackgroundService(IAppBroadcastBackgroundService const&) noexcept = default;
        IAppBroadcastBackgroundService(IAppBroadcastBackgroundService&&) noexcept = default;
        IAppBroadcastBackgroundService& operator=(IAppBroadcastBackgroundService const&) & noexcept = default;
        IAppBroadcastBackgroundService& operator=(IAppBroadcastBackgroundService&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastBackgroundService2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastBackgroundService2>
    {
        IAppBroadcastBackgroundService2(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastBackgroundService2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastBackgroundService2(IAppBroadcastBackgroundService2 const&) noexcept = default;
        IAppBroadcastBackgroundService2(IAppBroadcastBackgroundService2&&) noexcept = default;
        IAppBroadcastBackgroundService2& operator=(IAppBroadcastBackgroundService2 const&) & noexcept = default;
        IAppBroadcastBackgroundService2& operator=(IAppBroadcastBackgroundService2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastBackgroundServiceSignInInfo :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastBackgroundServiceSignInInfo>
    {
        IAppBroadcastBackgroundServiceSignInInfo(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastBackgroundServiceSignInInfo(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastBackgroundServiceSignInInfo(IAppBroadcastBackgroundServiceSignInInfo const&) noexcept = default;
        IAppBroadcastBackgroundServiceSignInInfo(IAppBroadcastBackgroundServiceSignInInfo&&) noexcept = default;
        IAppBroadcastBackgroundServiceSignInInfo& operator=(IAppBroadcastBackgroundServiceSignInInfo const&) & noexcept = default;
        IAppBroadcastBackgroundServiceSignInInfo& operator=(IAppBroadcastBackgroundServiceSignInInfo&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastBackgroundServiceSignInInfo2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastBackgroundServiceSignInInfo2>
    {
        IAppBroadcastBackgroundServiceSignInInfo2(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastBackgroundServiceSignInInfo2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastBackgroundServiceSignInInfo2(IAppBroadcastBackgroundServiceSignInInfo2 const&) noexcept = default;
        IAppBroadcastBackgroundServiceSignInInfo2(IAppBroadcastBackgroundServiceSignInInfo2&&) noexcept = default;
        IAppBroadcastBackgroundServiceSignInInfo2& operator=(IAppBroadcastBackgroundServiceSignInInfo2 const&) & noexcept = default;
        IAppBroadcastBackgroundServiceSignInInfo2& operator=(IAppBroadcastBackgroundServiceSignInInfo2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastBackgroundServiceStreamInfo :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastBackgroundServiceStreamInfo>
    {
        IAppBroadcastBackgroundServiceStreamInfo(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastBackgroundServiceStreamInfo(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastBackgroundServiceStreamInfo(IAppBroadcastBackgroundServiceStreamInfo const&) noexcept = default;
        IAppBroadcastBackgroundServiceStreamInfo(IAppBroadcastBackgroundServiceStreamInfo&&) noexcept = default;
        IAppBroadcastBackgroundServiceStreamInfo& operator=(IAppBroadcastBackgroundServiceStreamInfo const&) & noexcept = default;
        IAppBroadcastBackgroundServiceStreamInfo& operator=(IAppBroadcastBackgroundServiceStreamInfo&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastBackgroundServiceStreamInfo2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastBackgroundServiceStreamInfo2>
    {
        IAppBroadcastBackgroundServiceStreamInfo2(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastBackgroundServiceStreamInfo2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastBackgroundServiceStreamInfo2(IAppBroadcastBackgroundServiceStreamInfo2 const&) noexcept = default;
        IAppBroadcastBackgroundServiceStreamInfo2(IAppBroadcastBackgroundServiceStreamInfo2&&) noexcept = default;
        IAppBroadcastBackgroundServiceStreamInfo2& operator=(IAppBroadcastBackgroundServiceStreamInfo2 const&) & noexcept = default;
        IAppBroadcastBackgroundServiceStreamInfo2& operator=(IAppBroadcastBackgroundServiceStreamInfo2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastCameraCaptureStateChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastCameraCaptureStateChangedEventArgs>
    {
        IAppBroadcastCameraCaptureStateChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastCameraCaptureStateChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastCameraCaptureStateChangedEventArgs(IAppBroadcastCameraCaptureStateChangedEventArgs const&) noexcept = default;
        IAppBroadcastCameraCaptureStateChangedEventArgs(IAppBroadcastCameraCaptureStateChangedEventArgs&&) noexcept = default;
        IAppBroadcastCameraCaptureStateChangedEventArgs& operator=(IAppBroadcastCameraCaptureStateChangedEventArgs const&) & noexcept = default;
        IAppBroadcastCameraCaptureStateChangedEventArgs& operator=(IAppBroadcastCameraCaptureStateChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastGlobalSettings :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastGlobalSettings>
    {
        IAppBroadcastGlobalSettings(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastGlobalSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastGlobalSettings(IAppBroadcastGlobalSettings const&) noexcept = default;
        IAppBroadcastGlobalSettings(IAppBroadcastGlobalSettings&&) noexcept = default;
        IAppBroadcastGlobalSettings& operator=(IAppBroadcastGlobalSettings const&) & noexcept = default;
        IAppBroadcastGlobalSettings& operator=(IAppBroadcastGlobalSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastHeartbeatRequestedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastHeartbeatRequestedEventArgs>
    {
        IAppBroadcastHeartbeatRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastHeartbeatRequestedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastHeartbeatRequestedEventArgs(IAppBroadcastHeartbeatRequestedEventArgs const&) noexcept = default;
        IAppBroadcastHeartbeatRequestedEventArgs(IAppBroadcastHeartbeatRequestedEventArgs&&) noexcept = default;
        IAppBroadcastHeartbeatRequestedEventArgs& operator=(IAppBroadcastHeartbeatRequestedEventArgs const&) & noexcept = default;
        IAppBroadcastHeartbeatRequestedEventArgs& operator=(IAppBroadcastHeartbeatRequestedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastManagerStatics>
    {
        IAppBroadcastManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastManagerStatics(IAppBroadcastManagerStatics const&) noexcept = default;
        IAppBroadcastManagerStatics(IAppBroadcastManagerStatics&&) noexcept = default;
        IAppBroadcastManagerStatics& operator=(IAppBroadcastManagerStatics const&) & noexcept = default;
        IAppBroadcastManagerStatics& operator=(IAppBroadcastManagerStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastMicrophoneCaptureStateChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastMicrophoneCaptureStateChangedEventArgs>
    {
        IAppBroadcastMicrophoneCaptureStateChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastMicrophoneCaptureStateChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastMicrophoneCaptureStateChangedEventArgs(IAppBroadcastMicrophoneCaptureStateChangedEventArgs const&) noexcept = default;
        IAppBroadcastMicrophoneCaptureStateChangedEventArgs(IAppBroadcastMicrophoneCaptureStateChangedEventArgs&&) noexcept = default;
        IAppBroadcastMicrophoneCaptureStateChangedEventArgs& operator=(IAppBroadcastMicrophoneCaptureStateChangedEventArgs const&) & noexcept = default;
        IAppBroadcastMicrophoneCaptureStateChangedEventArgs& operator=(IAppBroadcastMicrophoneCaptureStateChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastPlugIn :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastPlugIn>
    {
        IAppBroadcastPlugIn(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastPlugIn(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastPlugIn(IAppBroadcastPlugIn const&) noexcept = default;
        IAppBroadcastPlugIn(IAppBroadcastPlugIn&&) noexcept = default;
        IAppBroadcastPlugIn& operator=(IAppBroadcastPlugIn const&) & noexcept = default;
        IAppBroadcastPlugIn& operator=(IAppBroadcastPlugIn&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastPlugInManager :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastPlugInManager>
    {
        IAppBroadcastPlugInManager(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastPlugInManager(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastPlugInManager(IAppBroadcastPlugInManager const&) noexcept = default;
        IAppBroadcastPlugInManager(IAppBroadcastPlugInManager&&) noexcept = default;
        IAppBroadcastPlugInManager& operator=(IAppBroadcastPlugInManager const&) & noexcept = default;
        IAppBroadcastPlugInManager& operator=(IAppBroadcastPlugInManager&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastPlugInManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastPlugInManagerStatics>
    {
        IAppBroadcastPlugInManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastPlugInManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastPlugInManagerStatics(IAppBroadcastPlugInManagerStatics const&) noexcept = default;
        IAppBroadcastPlugInManagerStatics(IAppBroadcastPlugInManagerStatics&&) noexcept = default;
        IAppBroadcastPlugInManagerStatics& operator=(IAppBroadcastPlugInManagerStatics const&) & noexcept = default;
        IAppBroadcastPlugInManagerStatics& operator=(IAppBroadcastPlugInManagerStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastPlugInStateChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastPlugInStateChangedEventArgs>
    {
        IAppBroadcastPlugInStateChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastPlugInStateChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastPlugInStateChangedEventArgs(IAppBroadcastPlugInStateChangedEventArgs const&) noexcept = default;
        IAppBroadcastPlugInStateChangedEventArgs(IAppBroadcastPlugInStateChangedEventArgs&&) noexcept = default;
        IAppBroadcastPlugInStateChangedEventArgs& operator=(IAppBroadcastPlugInStateChangedEventArgs const&) & noexcept = default;
        IAppBroadcastPlugInStateChangedEventArgs& operator=(IAppBroadcastPlugInStateChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastPreview :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastPreview>
    {
        IAppBroadcastPreview(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastPreview(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastPreview(IAppBroadcastPreview const&) noexcept = default;
        IAppBroadcastPreview(IAppBroadcastPreview&&) noexcept = default;
        IAppBroadcastPreview& operator=(IAppBroadcastPreview const&) & noexcept = default;
        IAppBroadcastPreview& operator=(IAppBroadcastPreview&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastPreviewStateChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastPreviewStateChangedEventArgs>
    {
        IAppBroadcastPreviewStateChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastPreviewStateChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastPreviewStateChangedEventArgs(IAppBroadcastPreviewStateChangedEventArgs const&) noexcept = default;
        IAppBroadcastPreviewStateChangedEventArgs(IAppBroadcastPreviewStateChangedEventArgs&&) noexcept = default;
        IAppBroadcastPreviewStateChangedEventArgs& operator=(IAppBroadcastPreviewStateChangedEventArgs const&) & noexcept = default;
        IAppBroadcastPreviewStateChangedEventArgs& operator=(IAppBroadcastPreviewStateChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastPreviewStreamReader :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastPreviewStreamReader>
    {
        IAppBroadcastPreviewStreamReader(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastPreviewStreamReader(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastPreviewStreamReader(IAppBroadcastPreviewStreamReader const&) noexcept = default;
        IAppBroadcastPreviewStreamReader(IAppBroadcastPreviewStreamReader&&) noexcept = default;
        IAppBroadcastPreviewStreamReader& operator=(IAppBroadcastPreviewStreamReader const&) & noexcept = default;
        IAppBroadcastPreviewStreamReader& operator=(IAppBroadcastPreviewStreamReader&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastPreviewStreamVideoFrame :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastPreviewStreamVideoFrame>
    {
        IAppBroadcastPreviewStreamVideoFrame(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastPreviewStreamVideoFrame(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastPreviewStreamVideoFrame(IAppBroadcastPreviewStreamVideoFrame const&) noexcept = default;
        IAppBroadcastPreviewStreamVideoFrame(IAppBroadcastPreviewStreamVideoFrame&&) noexcept = default;
        IAppBroadcastPreviewStreamVideoFrame& operator=(IAppBroadcastPreviewStreamVideoFrame const&) & noexcept = default;
        IAppBroadcastPreviewStreamVideoFrame& operator=(IAppBroadcastPreviewStreamVideoFrame&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastPreviewStreamVideoHeader :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastPreviewStreamVideoHeader>
    {
        IAppBroadcastPreviewStreamVideoHeader(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastPreviewStreamVideoHeader(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastPreviewStreamVideoHeader(IAppBroadcastPreviewStreamVideoHeader const&) noexcept = default;
        IAppBroadcastPreviewStreamVideoHeader(IAppBroadcastPreviewStreamVideoHeader&&) noexcept = default;
        IAppBroadcastPreviewStreamVideoHeader& operator=(IAppBroadcastPreviewStreamVideoHeader const&) & noexcept = default;
        IAppBroadcastPreviewStreamVideoHeader& operator=(IAppBroadcastPreviewStreamVideoHeader&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastProviderSettings :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastProviderSettings>
    {
        IAppBroadcastProviderSettings(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastProviderSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastProviderSettings(IAppBroadcastProviderSettings const&) noexcept = default;
        IAppBroadcastProviderSettings(IAppBroadcastProviderSettings&&) noexcept = default;
        IAppBroadcastProviderSettings& operator=(IAppBroadcastProviderSettings const&) & noexcept = default;
        IAppBroadcastProviderSettings& operator=(IAppBroadcastProviderSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastServices :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastServices>
    {
        IAppBroadcastServices(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastServices(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastServices(IAppBroadcastServices const&) noexcept = default;
        IAppBroadcastServices(IAppBroadcastServices&&) noexcept = default;
        IAppBroadcastServices& operator=(IAppBroadcastServices const&) & noexcept = default;
        IAppBroadcastServices& operator=(IAppBroadcastServices&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastSignInStateChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastSignInStateChangedEventArgs>
    {
        IAppBroadcastSignInStateChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastSignInStateChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastSignInStateChangedEventArgs(IAppBroadcastSignInStateChangedEventArgs const&) noexcept = default;
        IAppBroadcastSignInStateChangedEventArgs(IAppBroadcastSignInStateChangedEventArgs&&) noexcept = default;
        IAppBroadcastSignInStateChangedEventArgs& operator=(IAppBroadcastSignInStateChangedEventArgs const&) & noexcept = default;
        IAppBroadcastSignInStateChangedEventArgs& operator=(IAppBroadcastSignInStateChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastState :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastState>
    {
        IAppBroadcastState(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastState(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastState(IAppBroadcastState const&) noexcept = default;
        IAppBroadcastState(IAppBroadcastState&&) noexcept = default;
        IAppBroadcastState& operator=(IAppBroadcastState const&) & noexcept = default;
        IAppBroadcastState& operator=(IAppBroadcastState&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastStreamAudioFrame :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastStreamAudioFrame>
    {
        IAppBroadcastStreamAudioFrame(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastStreamAudioFrame(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastStreamAudioFrame(IAppBroadcastStreamAudioFrame const&) noexcept = default;
        IAppBroadcastStreamAudioFrame(IAppBroadcastStreamAudioFrame&&) noexcept = default;
        IAppBroadcastStreamAudioFrame& operator=(IAppBroadcastStreamAudioFrame const&) & noexcept = default;
        IAppBroadcastStreamAudioFrame& operator=(IAppBroadcastStreamAudioFrame&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastStreamAudioHeader :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastStreamAudioHeader>
    {
        IAppBroadcastStreamAudioHeader(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastStreamAudioHeader(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastStreamAudioHeader(IAppBroadcastStreamAudioHeader const&) noexcept = default;
        IAppBroadcastStreamAudioHeader(IAppBroadcastStreamAudioHeader&&) noexcept = default;
        IAppBroadcastStreamAudioHeader& operator=(IAppBroadcastStreamAudioHeader const&) & noexcept = default;
        IAppBroadcastStreamAudioHeader& operator=(IAppBroadcastStreamAudioHeader&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastStreamReader :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastStreamReader>
    {
        IAppBroadcastStreamReader(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastStreamReader(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastStreamReader(IAppBroadcastStreamReader const&) noexcept = default;
        IAppBroadcastStreamReader(IAppBroadcastStreamReader&&) noexcept = default;
        IAppBroadcastStreamReader& operator=(IAppBroadcastStreamReader const&) & noexcept = default;
        IAppBroadcastStreamReader& operator=(IAppBroadcastStreamReader&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastStreamStateChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastStreamStateChangedEventArgs>
    {
        IAppBroadcastStreamStateChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastStreamStateChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastStreamStateChangedEventArgs(IAppBroadcastStreamStateChangedEventArgs const&) noexcept = default;
        IAppBroadcastStreamStateChangedEventArgs(IAppBroadcastStreamStateChangedEventArgs&&) noexcept = default;
        IAppBroadcastStreamStateChangedEventArgs& operator=(IAppBroadcastStreamStateChangedEventArgs const&) & noexcept = default;
        IAppBroadcastStreamStateChangedEventArgs& operator=(IAppBroadcastStreamStateChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastStreamVideoFrame :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastStreamVideoFrame>
    {
        IAppBroadcastStreamVideoFrame(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastStreamVideoFrame(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastStreamVideoFrame(IAppBroadcastStreamVideoFrame const&) noexcept = default;
        IAppBroadcastStreamVideoFrame(IAppBroadcastStreamVideoFrame&&) noexcept = default;
        IAppBroadcastStreamVideoFrame& operator=(IAppBroadcastStreamVideoFrame const&) & noexcept = default;
        IAppBroadcastStreamVideoFrame& operator=(IAppBroadcastStreamVideoFrame&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastStreamVideoHeader :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastStreamVideoHeader>
    {
        IAppBroadcastStreamVideoHeader(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastStreamVideoHeader(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastStreamVideoHeader(IAppBroadcastStreamVideoHeader const&) noexcept = default;
        IAppBroadcastStreamVideoHeader(IAppBroadcastStreamVideoHeader&&) noexcept = default;
        IAppBroadcastStreamVideoHeader& operator=(IAppBroadcastStreamVideoHeader const&) & noexcept = default;
        IAppBroadcastStreamVideoHeader& operator=(IAppBroadcastStreamVideoHeader&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastTriggerDetails :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastTriggerDetails>
    {
        IAppBroadcastTriggerDetails(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastTriggerDetails(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastTriggerDetails(IAppBroadcastTriggerDetails const&) noexcept = default;
        IAppBroadcastTriggerDetails(IAppBroadcastTriggerDetails&&) noexcept = default;
        IAppBroadcastTriggerDetails& operator=(IAppBroadcastTriggerDetails const&) & noexcept = default;
        IAppBroadcastTriggerDetails& operator=(IAppBroadcastTriggerDetails&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppBroadcastViewerCountChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppBroadcastViewerCountChangedEventArgs>
    {
        IAppBroadcastViewerCountChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppBroadcastViewerCountChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppBroadcastViewerCountChangedEventArgs(IAppBroadcastViewerCountChangedEventArgs const&) noexcept = default;
        IAppBroadcastViewerCountChangedEventArgs(IAppBroadcastViewerCountChangedEventArgs&&) noexcept = default;
        IAppBroadcastViewerCountChangedEventArgs& operator=(IAppBroadcastViewerCountChangedEventArgs const&) & noexcept = default;
        IAppBroadcastViewerCountChangedEventArgs& operator=(IAppBroadcastViewerCountChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCapture :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCapture>
    {
        IAppCapture(std::nullptr_t = nullptr) noexcept {}
        IAppCapture(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCapture(IAppCapture const&) noexcept = default;
        IAppCapture(IAppCapture&&) noexcept = default;
        IAppCapture& operator=(IAppCapture const&) & noexcept = default;
        IAppCapture& operator=(IAppCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureAlternateShortcutKeys :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureAlternateShortcutKeys>
    {
        IAppCaptureAlternateShortcutKeys(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureAlternateShortcutKeys(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureAlternateShortcutKeys(IAppCaptureAlternateShortcutKeys const&) noexcept = default;
        IAppCaptureAlternateShortcutKeys(IAppCaptureAlternateShortcutKeys&&) noexcept = default;
        IAppCaptureAlternateShortcutKeys& operator=(IAppCaptureAlternateShortcutKeys const&) & noexcept = default;
        IAppCaptureAlternateShortcutKeys& operator=(IAppCaptureAlternateShortcutKeys&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureAlternateShortcutKeys2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureAlternateShortcutKeys2>
    {
        IAppCaptureAlternateShortcutKeys2(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureAlternateShortcutKeys2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureAlternateShortcutKeys2(IAppCaptureAlternateShortcutKeys2 const&) noexcept = default;
        IAppCaptureAlternateShortcutKeys2(IAppCaptureAlternateShortcutKeys2&&) noexcept = default;
        IAppCaptureAlternateShortcutKeys2& operator=(IAppCaptureAlternateShortcutKeys2 const&) & noexcept = default;
        IAppCaptureAlternateShortcutKeys2& operator=(IAppCaptureAlternateShortcutKeys2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureAlternateShortcutKeys3 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureAlternateShortcutKeys3>
    {
        IAppCaptureAlternateShortcutKeys3(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureAlternateShortcutKeys3(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureAlternateShortcutKeys3(IAppCaptureAlternateShortcutKeys3 const&) noexcept = default;
        IAppCaptureAlternateShortcutKeys3(IAppCaptureAlternateShortcutKeys3&&) noexcept = default;
        IAppCaptureAlternateShortcutKeys3& operator=(IAppCaptureAlternateShortcutKeys3 const&) & noexcept = default;
        IAppCaptureAlternateShortcutKeys3& operator=(IAppCaptureAlternateShortcutKeys3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureDurationGeneratedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureDurationGeneratedEventArgs>
    {
        IAppCaptureDurationGeneratedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureDurationGeneratedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureDurationGeneratedEventArgs(IAppCaptureDurationGeneratedEventArgs const&) noexcept = default;
        IAppCaptureDurationGeneratedEventArgs(IAppCaptureDurationGeneratedEventArgs&&) noexcept = default;
        IAppCaptureDurationGeneratedEventArgs& operator=(IAppCaptureDurationGeneratedEventArgs const&) & noexcept = default;
        IAppCaptureDurationGeneratedEventArgs& operator=(IAppCaptureDurationGeneratedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureFileGeneratedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureFileGeneratedEventArgs>
    {
        IAppCaptureFileGeneratedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureFileGeneratedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureFileGeneratedEventArgs(IAppCaptureFileGeneratedEventArgs const&) noexcept = default;
        IAppCaptureFileGeneratedEventArgs(IAppCaptureFileGeneratedEventArgs&&) noexcept = default;
        IAppCaptureFileGeneratedEventArgs& operator=(IAppCaptureFileGeneratedEventArgs const&) & noexcept = default;
        IAppCaptureFileGeneratedEventArgs& operator=(IAppCaptureFileGeneratedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureManagerStatics>
    {
        IAppCaptureManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureManagerStatics(IAppCaptureManagerStatics const&) noexcept = default;
        IAppCaptureManagerStatics(IAppCaptureManagerStatics&&) noexcept = default;
        IAppCaptureManagerStatics& operator=(IAppCaptureManagerStatics const&) & noexcept = default;
        IAppCaptureManagerStatics& operator=(IAppCaptureManagerStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureMetadataWriter :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureMetadataWriter>
    {
        IAppCaptureMetadataWriter(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureMetadataWriter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureMetadataWriter(IAppCaptureMetadataWriter const&) noexcept = default;
        IAppCaptureMetadataWriter(IAppCaptureMetadataWriter&&) noexcept = default;
        IAppCaptureMetadataWriter& operator=(IAppCaptureMetadataWriter const&) & noexcept = default;
        IAppCaptureMetadataWriter& operator=(IAppCaptureMetadataWriter&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureMicrophoneCaptureStateChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureMicrophoneCaptureStateChangedEventArgs>
    {
        IAppCaptureMicrophoneCaptureStateChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureMicrophoneCaptureStateChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureMicrophoneCaptureStateChangedEventArgs(IAppCaptureMicrophoneCaptureStateChangedEventArgs const&) noexcept = default;
        IAppCaptureMicrophoneCaptureStateChangedEventArgs(IAppCaptureMicrophoneCaptureStateChangedEventArgs&&) noexcept = default;
        IAppCaptureMicrophoneCaptureStateChangedEventArgs& operator=(IAppCaptureMicrophoneCaptureStateChangedEventArgs const&) & noexcept = default;
        IAppCaptureMicrophoneCaptureStateChangedEventArgs& operator=(IAppCaptureMicrophoneCaptureStateChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureRecordOperation :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureRecordOperation>
    {
        IAppCaptureRecordOperation(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureRecordOperation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureRecordOperation(IAppCaptureRecordOperation const&) noexcept = default;
        IAppCaptureRecordOperation(IAppCaptureRecordOperation&&) noexcept = default;
        IAppCaptureRecordOperation& operator=(IAppCaptureRecordOperation const&) & noexcept = default;
        IAppCaptureRecordOperation& operator=(IAppCaptureRecordOperation&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureRecordingStateChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureRecordingStateChangedEventArgs>
    {
        IAppCaptureRecordingStateChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureRecordingStateChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureRecordingStateChangedEventArgs(IAppCaptureRecordingStateChangedEventArgs const&) noexcept = default;
        IAppCaptureRecordingStateChangedEventArgs(IAppCaptureRecordingStateChangedEventArgs&&) noexcept = default;
        IAppCaptureRecordingStateChangedEventArgs& operator=(IAppCaptureRecordingStateChangedEventArgs const&) & noexcept = default;
        IAppCaptureRecordingStateChangedEventArgs& operator=(IAppCaptureRecordingStateChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureServices :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureServices>
    {
        IAppCaptureServices(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureServices(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureServices(IAppCaptureServices const&) noexcept = default;
        IAppCaptureServices(IAppCaptureServices&&) noexcept = default;
        IAppCaptureServices& operator=(IAppCaptureServices const&) & noexcept = default;
        IAppCaptureServices& operator=(IAppCaptureServices&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureSettings :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureSettings>
    {
        IAppCaptureSettings(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureSettings(IAppCaptureSettings const&) noexcept = default;
        IAppCaptureSettings(IAppCaptureSettings&&) noexcept = default;
        IAppCaptureSettings& operator=(IAppCaptureSettings const&) & noexcept = default;
        IAppCaptureSettings& operator=(IAppCaptureSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureSettings2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureSettings2>
    {
        IAppCaptureSettings2(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureSettings2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureSettings2(IAppCaptureSettings2 const&) noexcept = default;
        IAppCaptureSettings2(IAppCaptureSettings2&&) noexcept = default;
        IAppCaptureSettings2& operator=(IAppCaptureSettings2 const&) & noexcept = default;
        IAppCaptureSettings2& operator=(IAppCaptureSettings2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureSettings3 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureSettings3>
    {
        IAppCaptureSettings3(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureSettings3(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureSettings3(IAppCaptureSettings3 const&) noexcept = default;
        IAppCaptureSettings3(IAppCaptureSettings3&&) noexcept = default;
        IAppCaptureSettings3& operator=(IAppCaptureSettings3 const&) & noexcept = default;
        IAppCaptureSettings3& operator=(IAppCaptureSettings3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureSettings4 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureSettings4>
    {
        IAppCaptureSettings4(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureSettings4(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureSettings4(IAppCaptureSettings4 const&) noexcept = default;
        IAppCaptureSettings4(IAppCaptureSettings4&&) noexcept = default;
        IAppCaptureSettings4& operator=(IAppCaptureSettings4 const&) & noexcept = default;
        IAppCaptureSettings4& operator=(IAppCaptureSettings4&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureSettings5 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureSettings5>
    {
        IAppCaptureSettings5(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureSettings5(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureSettings5(IAppCaptureSettings5 const&) noexcept = default;
        IAppCaptureSettings5(IAppCaptureSettings5&&) noexcept = default;
        IAppCaptureSettings5& operator=(IAppCaptureSettings5 const&) & noexcept = default;
        IAppCaptureSettings5& operator=(IAppCaptureSettings5&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureState :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureState>
    {
        IAppCaptureState(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureState(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureState(IAppCaptureState const&) noexcept = default;
        IAppCaptureState(IAppCaptureState&&) noexcept = default;
        IAppCaptureState& operator=(IAppCaptureState const&) & noexcept = default;
        IAppCaptureState& operator=(IAppCaptureState&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureStatics>
    {
        IAppCaptureStatics(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureStatics(IAppCaptureStatics const&) noexcept = default;
        IAppCaptureStatics(IAppCaptureStatics&&) noexcept = default;
        IAppCaptureStatics& operator=(IAppCaptureStatics const&) & noexcept = default;
        IAppCaptureStatics& operator=(IAppCaptureStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IAppCaptureStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IAppCaptureStatics2>
    {
        IAppCaptureStatics2(std::nullptr_t = nullptr) noexcept {}
        IAppCaptureStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IAppCaptureStatics2(IAppCaptureStatics2 const&) noexcept = default;
        IAppCaptureStatics2(IAppCaptureStatics2&&) noexcept = default;
        IAppCaptureStatics2& operator=(IAppCaptureStatics2 const&) & noexcept = default;
        IAppCaptureStatics2& operator=(IAppCaptureStatics2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICameraCaptureUI :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICameraCaptureUI>
    {
        ICameraCaptureUI(std::nullptr_t = nullptr) noexcept {}
        ICameraCaptureUI(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICameraCaptureUI(ICameraCaptureUI const&) noexcept = default;
        ICameraCaptureUI(ICameraCaptureUI&&) noexcept = default;
        ICameraCaptureUI& operator=(ICameraCaptureUI const&) & noexcept = default;
        ICameraCaptureUI& operator=(ICameraCaptureUI&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICameraCaptureUIPhotoCaptureSettings :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICameraCaptureUIPhotoCaptureSettings>
    {
        ICameraCaptureUIPhotoCaptureSettings(std::nullptr_t = nullptr) noexcept {}
        ICameraCaptureUIPhotoCaptureSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICameraCaptureUIPhotoCaptureSettings(ICameraCaptureUIPhotoCaptureSettings const&) noexcept = default;
        ICameraCaptureUIPhotoCaptureSettings(ICameraCaptureUIPhotoCaptureSettings&&) noexcept = default;
        ICameraCaptureUIPhotoCaptureSettings& operator=(ICameraCaptureUIPhotoCaptureSettings const&) & noexcept = default;
        ICameraCaptureUIPhotoCaptureSettings& operator=(ICameraCaptureUIPhotoCaptureSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICameraCaptureUIVideoCaptureSettings :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICameraCaptureUIVideoCaptureSettings>
    {
        ICameraCaptureUIVideoCaptureSettings(std::nullptr_t = nullptr) noexcept {}
        ICameraCaptureUIVideoCaptureSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICameraCaptureUIVideoCaptureSettings(ICameraCaptureUIVideoCaptureSettings const&) noexcept = default;
        ICameraCaptureUIVideoCaptureSettings(ICameraCaptureUIVideoCaptureSettings&&) noexcept = default;
        ICameraCaptureUIVideoCaptureSettings& operator=(ICameraCaptureUIVideoCaptureSettings const&) & noexcept = default;
        ICameraCaptureUIVideoCaptureSettings& operator=(ICameraCaptureUIVideoCaptureSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICameraOptionsUIStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICameraOptionsUIStatics>
    {
        ICameraOptionsUIStatics(std::nullptr_t = nullptr) noexcept {}
        ICameraOptionsUIStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICameraOptionsUIStatics(ICameraOptionsUIStatics const&) noexcept = default;
        ICameraOptionsUIStatics(ICameraOptionsUIStatics&&) noexcept = default;
        ICameraOptionsUIStatics& operator=(ICameraOptionsUIStatics const&) & noexcept = default;
        ICameraOptionsUIStatics& operator=(ICameraOptionsUIStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedFrame :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedFrame>,
        impl::require<Windows::Media::Capture::ICapturedFrame, Windows::Foundation::IClosable, Windows::Storage::Streams::IInputStream, Windows::Storage::Streams::IOutputStream, Windows::Storage::Streams::IRandomAccessStream, Windows::Storage::Streams::IContentTypeProvider, Windows::Storage::Streams::IRandomAccessStreamWithContentType>
    {
        ICapturedFrame(std::nullptr_t = nullptr) noexcept {}
        ICapturedFrame(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedFrame(ICapturedFrame const&) noexcept = default;
        ICapturedFrame(ICapturedFrame&&) noexcept = default;
        ICapturedFrame& operator=(ICapturedFrame const&) & noexcept = default;
        ICapturedFrame& operator=(ICapturedFrame&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedFrame2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedFrame2>
    {
        ICapturedFrame2(std::nullptr_t = nullptr) noexcept {}
        ICapturedFrame2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedFrame2(ICapturedFrame2 const&) noexcept = default;
        ICapturedFrame2(ICapturedFrame2&&) noexcept = default;
        ICapturedFrame2& operator=(ICapturedFrame2 const&) & noexcept = default;
        ICapturedFrame2& operator=(ICapturedFrame2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedFrameControlValues :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedFrameControlValues>
    {
        ICapturedFrameControlValues(std::nullptr_t = nullptr) noexcept {}
        ICapturedFrameControlValues(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedFrameControlValues(ICapturedFrameControlValues const&) noexcept = default;
        ICapturedFrameControlValues(ICapturedFrameControlValues&&) noexcept = default;
        ICapturedFrameControlValues& operator=(ICapturedFrameControlValues const&) & noexcept = default;
        ICapturedFrameControlValues& operator=(ICapturedFrameControlValues&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedFrameControlValues2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedFrameControlValues2>
    {
        ICapturedFrameControlValues2(std::nullptr_t = nullptr) noexcept {}
        ICapturedFrameControlValues2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedFrameControlValues2(ICapturedFrameControlValues2 const&) noexcept = default;
        ICapturedFrameControlValues2(ICapturedFrameControlValues2&&) noexcept = default;
        ICapturedFrameControlValues2& operator=(ICapturedFrameControlValues2 const&) & noexcept = default;
        ICapturedFrameControlValues2& operator=(ICapturedFrameControlValues2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedFrameWithSoftwareBitmap :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedFrameWithSoftwareBitmap>
    {
        ICapturedFrameWithSoftwareBitmap(std::nullptr_t = nullptr) noexcept {}
        ICapturedFrameWithSoftwareBitmap(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedFrameWithSoftwareBitmap(ICapturedFrameWithSoftwareBitmap const&) noexcept = default;
        ICapturedFrameWithSoftwareBitmap(ICapturedFrameWithSoftwareBitmap&&) noexcept = default;
        ICapturedFrameWithSoftwareBitmap& operator=(ICapturedFrameWithSoftwareBitmap const&) & noexcept = default;
        ICapturedFrameWithSoftwareBitmap& operator=(ICapturedFrameWithSoftwareBitmap&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ICapturedPhoto :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICapturedPhoto>
    {
        ICapturedPhoto(std::nullptr_t = nullptr) noexcept {}
        ICapturedPhoto(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ICapturedPhoto(ICapturedPhoto const&) noexcept = default;
        ICapturedPhoto(ICapturedPhoto&&) noexcept = default;
        ICapturedPhoto& operator=(ICapturedPhoto const&) & noexcept = default;
        ICapturedPhoto& operator=(ICapturedPhoto&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IGameBarServices :
        Windows::Foundation::IInspectable,
        impl::consume_t<IGameBarServices>
    {
        IGameBarServices(std::nullptr_t = nullptr) noexcept {}
        IGameBarServices(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IGameBarServices(IGameBarServices const&) noexcept = default;
        IGameBarServices(IGameBarServices&&) noexcept = default;
        IGameBarServices& operator=(IGameBarServices const&) & noexcept = default;
        IGameBarServices& operator=(IGameBarServices&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IGameBarServicesCommandEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IGameBarServicesCommandEventArgs>
    {
        IGameBarServicesCommandEventArgs(std::nullptr_t = nullptr) noexcept {}
        IGameBarServicesCommandEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IGameBarServicesCommandEventArgs(IGameBarServicesCommandEventArgs const&) noexcept = default;
        IGameBarServicesCommandEventArgs(IGameBarServicesCommandEventArgs&&) noexcept = default;
        IGameBarServicesCommandEventArgs& operator=(IGameBarServicesCommandEventArgs const&) & noexcept = default;
        IGameBarServicesCommandEventArgs& operator=(IGameBarServicesCommandEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IGameBarServicesManager :
        Windows::Foundation::IInspectable,
        impl::consume_t<IGameBarServicesManager>
    {
        IGameBarServicesManager(std::nullptr_t = nullptr) noexcept {}
        IGameBarServicesManager(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IGameBarServicesManager(IGameBarServicesManager const&) noexcept = default;
        IGameBarServicesManager(IGameBarServicesManager&&) noexcept = default;
        IGameBarServicesManager& operator=(IGameBarServicesManager const&) & noexcept = default;
        IGameBarServicesManager& operator=(IGameBarServicesManager&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IGameBarServicesManagerGameBarServicesCreatedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IGameBarServicesManagerGameBarServicesCreatedEventArgs>
    {
        IGameBarServicesManagerGameBarServicesCreatedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IGameBarServicesManagerGameBarServicesCreatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IGameBarServicesManagerGameBarServicesCreatedEventArgs(IGameBarServicesManagerGameBarServicesCreatedEventArgs const&) noexcept = default;
        IGameBarServicesManagerGameBarServicesCreatedEventArgs(IGameBarServicesManagerGameBarServicesCreatedEventArgs&&) noexcept = default;
        IGameBarServicesManagerGameBarServicesCreatedEventArgs& operator=(IGameBarServicesManagerGameBarServicesCreatedEventArgs const&) & noexcept = default;
        IGameBarServicesManagerGameBarServicesCreatedEventArgs& operator=(IGameBarServicesManagerGameBarServicesCreatedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IGameBarServicesManagerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IGameBarServicesManagerStatics>
    {
        IGameBarServicesManagerStatics(std::nullptr_t = nullptr) noexcept {}
        IGameBarServicesManagerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IGameBarServicesManagerStatics(IGameBarServicesManagerStatics const&) noexcept = default;
        IGameBarServicesManagerStatics(IGameBarServicesManagerStatics&&) noexcept = default;
        IGameBarServicesManagerStatics& operator=(IGameBarServicesManagerStatics const&) & noexcept = default;
        IGameBarServicesManagerStatics& operator=(IGameBarServicesManagerStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IGameBarServicesTargetInfo :
        Windows::Foundation::IInspectable,
        impl::consume_t<IGameBarServicesTargetInfo>
    {
        IGameBarServicesTargetInfo(std::nullptr_t = nullptr) noexcept {}
        IGameBarServicesTargetInfo(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IGameBarServicesTargetInfo(IGameBarServicesTargetInfo const&) noexcept = default;
        IGameBarServicesTargetInfo(IGameBarServicesTargetInfo&&) noexcept = default;
        IGameBarServicesTargetInfo& operator=(IGameBarServicesTargetInfo const&) & noexcept = default;
        IGameBarServicesTargetInfo& operator=(IGameBarServicesTargetInfo&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ILowLagMediaRecording :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILowLagMediaRecording>
    {
        ILowLagMediaRecording(std::nullptr_t = nullptr) noexcept {}
        ILowLagMediaRecording(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ILowLagMediaRecording(ILowLagMediaRecording const&) noexcept = default;
        ILowLagMediaRecording(ILowLagMediaRecording&&) noexcept = default;
        ILowLagMediaRecording& operator=(ILowLagMediaRecording const&) & noexcept = default;
        ILowLagMediaRecording& operator=(ILowLagMediaRecording&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ILowLagMediaRecording2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILowLagMediaRecording2>
    {
        ILowLagMediaRecording2(std::nullptr_t = nullptr) noexcept {}
        ILowLagMediaRecording2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ILowLagMediaRecording2(ILowLagMediaRecording2 const&) noexcept = default;
        ILowLagMediaRecording2(ILowLagMediaRecording2&&) noexcept = default;
        ILowLagMediaRecording2& operator=(ILowLagMediaRecording2 const&) & noexcept = default;
        ILowLagMediaRecording2& operator=(ILowLagMediaRecording2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ILowLagMediaRecording3 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILowLagMediaRecording3>
    {
        ILowLagMediaRecording3(std::nullptr_t = nullptr) noexcept {}
        ILowLagMediaRecording3(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ILowLagMediaRecording3(ILowLagMediaRecording3 const&) noexcept = default;
        ILowLagMediaRecording3(ILowLagMediaRecording3&&) noexcept = default;
        ILowLagMediaRecording3& operator=(ILowLagMediaRecording3 const&) & noexcept = default;
        ILowLagMediaRecording3& operator=(ILowLagMediaRecording3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ILowLagPhotoCapture :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILowLagPhotoCapture>
    {
        ILowLagPhotoCapture(std::nullptr_t = nullptr) noexcept {}
        ILowLagPhotoCapture(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ILowLagPhotoCapture(ILowLagPhotoCapture const&) noexcept = default;
        ILowLagPhotoCapture(ILowLagPhotoCapture&&) noexcept = default;
        ILowLagPhotoCapture& operator=(ILowLagPhotoCapture const&) & noexcept = default;
        ILowLagPhotoCapture& operator=(ILowLagPhotoCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ILowLagPhotoSequenceCapture :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILowLagPhotoSequenceCapture>
    {
        ILowLagPhotoSequenceCapture(std::nullptr_t = nullptr) noexcept {}
        ILowLagPhotoSequenceCapture(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ILowLagPhotoSequenceCapture(ILowLagPhotoSequenceCapture const&) noexcept = default;
        ILowLagPhotoSequenceCapture(ILowLagPhotoSequenceCapture&&) noexcept = default;
        ILowLagPhotoSequenceCapture& operator=(ILowLagPhotoSequenceCapture const&) & noexcept = default;
        ILowLagPhotoSequenceCapture& operator=(ILowLagPhotoSequenceCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture>
    {
        IMediaCapture(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture(IMediaCapture const&) noexcept = default;
        IMediaCapture(IMediaCapture&&) noexcept = default;
        IMediaCapture& operator=(IMediaCapture const&) & noexcept = default;
        IMediaCapture& operator=(IMediaCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture2>
    {
        IMediaCapture2(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture2(IMediaCapture2 const&) noexcept = default;
        IMediaCapture2(IMediaCapture2&&) noexcept = default;
        IMediaCapture2& operator=(IMediaCapture2 const&) & noexcept = default;
        IMediaCapture2& operator=(IMediaCapture2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture3 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture3>
    {
        IMediaCapture3(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture3(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture3(IMediaCapture3 const&) noexcept = default;
        IMediaCapture3(IMediaCapture3&&) noexcept = default;
        IMediaCapture3& operator=(IMediaCapture3 const&) & noexcept = default;
        IMediaCapture3& operator=(IMediaCapture3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture4 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture4>
    {
        IMediaCapture4(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture4(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture4(IMediaCapture4 const&) noexcept = default;
        IMediaCapture4(IMediaCapture4&&) noexcept = default;
        IMediaCapture4& operator=(IMediaCapture4 const&) & noexcept = default;
        IMediaCapture4& operator=(IMediaCapture4&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture5 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture5>
    {
        IMediaCapture5(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture5(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture5(IMediaCapture5 const&) noexcept = default;
        IMediaCapture5(IMediaCapture5&&) noexcept = default;
        IMediaCapture5& operator=(IMediaCapture5 const&) & noexcept = default;
        IMediaCapture5& operator=(IMediaCapture5&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapture6 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapture6>
    {
        IMediaCapture6(std::nullptr_t = nullptr) noexcept {}
        IMediaCapture6(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapture6(IMediaCapture6 const&) noexcept = default;
        IMediaCapture6(IMediaCapture6&&) noexcept = default;
        IMediaCapture6& operator=(IMediaCapture6 const&) & noexcept = default;
        IMediaCapture6& operator=(IMediaCapture6&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs>
    {
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs(IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs const&) noexcept = default;
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs(IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs&&) noexcept = default;
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs& operator=(IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs const&) & noexcept = default;
        IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs& operator=(IMediaCaptureDeviceExclusiveControlStatusChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureFailedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureFailedEventArgs>
    {
        IMediaCaptureFailedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureFailedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureFailedEventArgs(IMediaCaptureFailedEventArgs const&) noexcept = default;
        IMediaCaptureFailedEventArgs(IMediaCaptureFailedEventArgs&&) noexcept = default;
        IMediaCaptureFailedEventArgs& operator=(IMediaCaptureFailedEventArgs const&) & noexcept = default;
        IMediaCaptureFailedEventArgs& operator=(IMediaCaptureFailedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureFocusChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureFocusChangedEventArgs>
    {
        IMediaCaptureFocusChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureFocusChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureFocusChangedEventArgs(IMediaCaptureFocusChangedEventArgs const&) noexcept = default;
        IMediaCaptureFocusChangedEventArgs(IMediaCaptureFocusChangedEventArgs&&) noexcept = default;
        IMediaCaptureFocusChangedEventArgs& operator=(IMediaCaptureFocusChangedEventArgs const&) & noexcept = default;
        IMediaCaptureFocusChangedEventArgs& operator=(IMediaCaptureFocusChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings>
    {
        IMediaCaptureInitializationSettings(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings(IMediaCaptureInitializationSettings const&) noexcept = default;
        IMediaCaptureInitializationSettings(IMediaCaptureInitializationSettings&&) noexcept = default;
        IMediaCaptureInitializationSettings& operator=(IMediaCaptureInitializationSettings const&) & noexcept = default;
        IMediaCaptureInitializationSettings& operator=(IMediaCaptureInitializationSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings2>
    {
        IMediaCaptureInitializationSettings2(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings2(IMediaCaptureInitializationSettings2 const&) noexcept = default;
        IMediaCaptureInitializationSettings2(IMediaCaptureInitializationSettings2&&) noexcept = default;
        IMediaCaptureInitializationSettings2& operator=(IMediaCaptureInitializationSettings2 const&) & noexcept = default;
        IMediaCaptureInitializationSettings2& operator=(IMediaCaptureInitializationSettings2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings3 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings3>
    {
        IMediaCaptureInitializationSettings3(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings3(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings3(IMediaCaptureInitializationSettings3 const&) noexcept = default;
        IMediaCaptureInitializationSettings3(IMediaCaptureInitializationSettings3&&) noexcept = default;
        IMediaCaptureInitializationSettings3& operator=(IMediaCaptureInitializationSettings3 const&) & noexcept = default;
        IMediaCaptureInitializationSettings3& operator=(IMediaCaptureInitializationSettings3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings4 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings4>
    {
        IMediaCaptureInitializationSettings4(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings4(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings4(IMediaCaptureInitializationSettings4 const&) noexcept = default;
        IMediaCaptureInitializationSettings4(IMediaCaptureInitializationSettings4&&) noexcept = default;
        IMediaCaptureInitializationSettings4& operator=(IMediaCaptureInitializationSettings4 const&) & noexcept = default;
        IMediaCaptureInitializationSettings4& operator=(IMediaCaptureInitializationSettings4&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings5 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings5>
    {
        IMediaCaptureInitializationSettings5(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings5(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings5(IMediaCaptureInitializationSettings5 const&) noexcept = default;
        IMediaCaptureInitializationSettings5(IMediaCaptureInitializationSettings5&&) noexcept = default;
        IMediaCaptureInitializationSettings5& operator=(IMediaCaptureInitializationSettings5 const&) & noexcept = default;
        IMediaCaptureInitializationSettings5& operator=(IMediaCaptureInitializationSettings5&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureInitializationSettings6 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureInitializationSettings6>
    {
        IMediaCaptureInitializationSettings6(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureInitializationSettings6(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureInitializationSettings6(IMediaCaptureInitializationSettings6 const&) noexcept = default;
        IMediaCaptureInitializationSettings6(IMediaCaptureInitializationSettings6&&) noexcept = default;
        IMediaCaptureInitializationSettings6& operator=(IMediaCaptureInitializationSettings6 const&) & noexcept = default;
        IMediaCaptureInitializationSettings6& operator=(IMediaCaptureInitializationSettings6&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCapturePauseResult :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCapturePauseResult>
    {
        IMediaCapturePauseResult(std::nullptr_t = nullptr) noexcept {}
        IMediaCapturePauseResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCapturePauseResult(IMediaCapturePauseResult const&) noexcept = default;
        IMediaCapturePauseResult(IMediaCapturePauseResult&&) noexcept = default;
        IMediaCapturePauseResult& operator=(IMediaCapturePauseResult const&) & noexcept = default;
        IMediaCapturePauseResult& operator=(IMediaCapturePauseResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureSettings :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureSettings>
    {
        IMediaCaptureSettings(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureSettings(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureSettings(IMediaCaptureSettings const&) noexcept = default;
        IMediaCaptureSettings(IMediaCaptureSettings&&) noexcept = default;
        IMediaCaptureSettings& operator=(IMediaCaptureSettings const&) & noexcept = default;
        IMediaCaptureSettings& operator=(IMediaCaptureSettings&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureSettings2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureSettings2>
    {
        IMediaCaptureSettings2(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureSettings2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureSettings2(IMediaCaptureSettings2 const&) noexcept = default;
        IMediaCaptureSettings2(IMediaCaptureSettings2&&) noexcept = default;
        IMediaCaptureSettings2& operator=(IMediaCaptureSettings2 const&) & noexcept = default;
        IMediaCaptureSettings2& operator=(IMediaCaptureSettings2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureSettings3 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureSettings3>
    {
        IMediaCaptureSettings3(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureSettings3(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureSettings3(IMediaCaptureSettings3 const&) noexcept = default;
        IMediaCaptureSettings3(IMediaCaptureSettings3&&) noexcept = default;
        IMediaCaptureSettings3& operator=(IMediaCaptureSettings3 const&) & noexcept = default;
        IMediaCaptureSettings3& operator=(IMediaCaptureSettings3&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureStatics>
    {
        IMediaCaptureStatics(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureStatics(IMediaCaptureStatics const&) noexcept = default;
        IMediaCaptureStatics(IMediaCaptureStatics&&) noexcept = default;
        IMediaCaptureStatics& operator=(IMediaCaptureStatics const&) & noexcept = default;
        IMediaCaptureStatics& operator=(IMediaCaptureStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureStopResult :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureStopResult>
    {
        IMediaCaptureStopResult(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureStopResult(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureStopResult(IMediaCaptureStopResult const&) noexcept = default;
        IMediaCaptureStopResult(IMediaCaptureStopResult&&) noexcept = default;
        IMediaCaptureStopResult& operator=(IMediaCaptureStopResult const&) & noexcept = default;
        IMediaCaptureStopResult& operator=(IMediaCaptureStopResult&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureVideoPreview :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureVideoPreview>
    {
        IMediaCaptureVideoPreview(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureVideoPreview(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureVideoPreview(IMediaCaptureVideoPreview const&) noexcept = default;
        IMediaCaptureVideoPreview(IMediaCaptureVideoPreview&&) noexcept = default;
        IMediaCaptureVideoPreview& operator=(IMediaCaptureVideoPreview const&) & noexcept = default;
        IMediaCaptureVideoPreview& operator=(IMediaCaptureVideoPreview&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureVideoProfile :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureVideoProfile>
    {
        IMediaCaptureVideoProfile(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureVideoProfile(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureVideoProfile(IMediaCaptureVideoProfile const&) noexcept = default;
        IMediaCaptureVideoProfile(IMediaCaptureVideoProfile&&) noexcept = default;
        IMediaCaptureVideoProfile& operator=(IMediaCaptureVideoProfile const&) & noexcept = default;
        IMediaCaptureVideoProfile& operator=(IMediaCaptureVideoProfile&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureVideoProfile2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureVideoProfile2>
    {
        IMediaCaptureVideoProfile2(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureVideoProfile2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureVideoProfile2(IMediaCaptureVideoProfile2 const&) noexcept = default;
        IMediaCaptureVideoProfile2(IMediaCaptureVideoProfile2&&) noexcept = default;
        IMediaCaptureVideoProfile2& operator=(IMediaCaptureVideoProfile2 const&) & noexcept = default;
        IMediaCaptureVideoProfile2& operator=(IMediaCaptureVideoProfile2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureVideoProfileMediaDescription :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureVideoProfileMediaDescription>
    {
        IMediaCaptureVideoProfileMediaDescription(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureVideoProfileMediaDescription(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureVideoProfileMediaDescription(IMediaCaptureVideoProfileMediaDescription const&) noexcept = default;
        IMediaCaptureVideoProfileMediaDescription(IMediaCaptureVideoProfileMediaDescription&&) noexcept = default;
        IMediaCaptureVideoProfileMediaDescription& operator=(IMediaCaptureVideoProfileMediaDescription const&) & noexcept = default;
        IMediaCaptureVideoProfileMediaDescription& operator=(IMediaCaptureVideoProfileMediaDescription&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IMediaCaptureVideoProfileMediaDescription2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMediaCaptureVideoProfileMediaDescription2>
    {
        IMediaCaptureVideoProfileMediaDescription2(std::nullptr_t = nullptr) noexcept {}
        IMediaCaptureVideoProfileMediaDescription2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IMediaCaptureVideoProfileMediaDescription2(IMediaCaptureVideoProfileMediaDescription2 const&) noexcept = default;
        IMediaCaptureVideoProfileMediaDescription2(IMediaCaptureVideoProfileMediaDescription2&&) noexcept = default;
        IMediaCaptureVideoProfileMediaDescription2& operator=(IMediaCaptureVideoProfileMediaDescription2 const&) & noexcept = default;
        IMediaCaptureVideoProfileMediaDescription2& operator=(IMediaCaptureVideoProfileMediaDescription2&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IOptionalReferencePhotoCapturedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IOptionalReferencePhotoCapturedEventArgs>
    {
        IOptionalReferencePhotoCapturedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IOptionalReferencePhotoCapturedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IOptionalReferencePhotoCapturedEventArgs(IOptionalReferencePhotoCapturedEventArgs const&) noexcept = default;
        IOptionalReferencePhotoCapturedEventArgs(IOptionalReferencePhotoCapturedEventArgs&&) noexcept = default;
        IOptionalReferencePhotoCapturedEventArgs& operator=(IOptionalReferencePhotoCapturedEventArgs const&) & noexcept = default;
        IOptionalReferencePhotoCapturedEventArgs& operator=(IOptionalReferencePhotoCapturedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPhotoCapturedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhotoCapturedEventArgs>
    {
        IPhotoCapturedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IPhotoCapturedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPhotoCapturedEventArgs(IPhotoCapturedEventArgs const&) noexcept = default;
        IPhotoCapturedEventArgs(IPhotoCapturedEventArgs&&) noexcept = default;
        IPhotoCapturedEventArgs& operator=(IPhotoCapturedEventArgs const&) & noexcept = default;
        IPhotoCapturedEventArgs& operator=(IPhotoCapturedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IPhotoConfirmationCapturedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPhotoConfirmationCapturedEventArgs>
    {
        IPhotoConfirmationCapturedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IPhotoConfirmationCapturedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IPhotoConfirmationCapturedEventArgs(IPhotoConfirmationCapturedEventArgs const&) noexcept = default;
        IPhotoConfirmationCapturedEventArgs(IPhotoConfirmationCapturedEventArgs&&) noexcept = default;
        IPhotoConfirmationCapturedEventArgs& operator=(IPhotoConfirmationCapturedEventArgs const&) & noexcept = default;
        IPhotoConfirmationCapturedEventArgs& operator=(IPhotoConfirmationCapturedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IScreenCapture :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScreenCapture>
    {
        IScreenCapture(std::nullptr_t = nullptr) noexcept {}
        IScreenCapture(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IScreenCapture(IScreenCapture const&) noexcept = default;
        IScreenCapture(IScreenCapture&&) noexcept = default;
        IScreenCapture& operator=(IScreenCapture const&) & noexcept = default;
        IScreenCapture& operator=(IScreenCapture&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IScreenCaptureStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IScreenCaptureStatics>
    {
        IScreenCaptureStatics(std::nullptr_t = nullptr) noexcept {}
        IScreenCaptureStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IScreenCaptureStatics(IScreenCaptureStatics const&) noexcept = default;
        IScreenCaptureStatics(IScreenCaptureStatics&&) noexcept = default;
        IScreenCaptureStatics& operator=(IScreenCaptureStatics const&) & noexcept = default;
        IScreenCaptureStatics& operator=(IScreenCaptureStatics&&) & noexcept = default;
    };
    struct __declspec(empty_bases) ISourceSuspensionChangedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISourceSuspensionChangedEventArgs>
    {
        ISourceSuspensionChangedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ISourceSuspensionChangedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        ISourceSuspensionChangedEventArgs(ISourceSuspensionChangedEventArgs const&) noexcept = default;
        ISourceSuspensionChangedEventArgs(ISourceSuspensionChangedEventArgs&&) noexcept = default;
        ISourceSuspensionChangedEventArgs& operator=(ISourceSuspensionChangedEventArgs const&) & noexcept = default;
        ISourceSuspensionChangedEventArgs& operator=(ISourceSuspensionChangedEventArgs&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IVideoStreamConfiguration :
        Windows::Foundation::IInspectable,
        impl::consume_t<IVideoStreamConfiguration>
    {
        IVideoStreamConfiguration(std::nullptr_t = nullptr) noexcept {}
        IVideoStreamConfiguration(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IVideoStreamConfiguration(IVideoStreamConfiguration const&) noexcept = default;
        IVideoStreamConfiguration(IVideoStreamConfiguration&&) noexcept = default;
        IVideoStreamConfiguration& operator=(IVideoStreamConfiguration const&) & noexcept = default;
        IVideoStreamConfiguration& operator=(IVideoStreamConfiguration&&) & noexcept = default;
    };
}
#endif
