// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210211.2

#ifndef WINRT_Windows_Embedded_DeviceLockdown_1_H
#define WINRT_Windows_Embedded_DeviceLockdown_1_H
#include "winrt/impl/Windows.Embedded.DeviceLockdown.0.h"
WINRT_EXPORT namespace winrt::Windows::Embedded::DeviceLockdown
{
    struct __declspec(empty_bases) IDeviceLockdownProfileInformation :
        Windows::Foundation::IInspectable,
        impl::consume_t<IDeviceLockdownProfileInformation>
    {
        IDeviceLockdownProfileInformation(std::nullptr_t = nullptr) noexcept {}
        IDeviceLockdownProfileInformation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IDeviceLockdownProfileInformation(IDeviceLockdownProfileInformation const&) noexcept = default;
        IDeviceLockdownProfileInformation(IDeviceLockdownProfileInformation&&) noexcept = default;
        IDeviceLockdownProfileInformation& operator=(IDeviceLockdownProfileInformation const&) & noexcept = default;
        IDeviceLockdownProfileInformation& operator=(IDeviceLockdownProfileInformation&&) & noexcept = default;
    };
    struct __declspec(empty_bases) IDeviceLockdownProfileStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IDeviceLockdownProfileStatics>
    {
        IDeviceLockdownProfileStatics(std::nullptr_t = nullptr) noexcept {}
        IDeviceLockdownProfileStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
        IDeviceLockdownProfileStatics(IDeviceLockdownProfileStatics const&) noexcept = default;
        IDeviceLockdownProfileStatics(IDeviceLockdownProfileStatics&&) noexcept = default;
        IDeviceLockdownProfileStatics& operator=(IDeviceLockdownProfileStatics const&) & noexcept = default;
        IDeviceLockdownProfileStatics& operator=(IDeviceLockdownProfileStatics&&) & noexcept = default;
    };
}
#endif
